### ISSUE TITLE
to add

### ISSUE THREAD

**Issue by tsulej** [osromusic/Glitch-Arts-Resources#2]
Hi, you may want to add source code collection of various glitch tools found on github:

https://github.com/GlitchTools

also

we have group related to techniques: https://www.facebook.com/groups/GACToolTime/

**Comment by osromusic** [comment]
Thanks for the suggestions!

I have added those links - but, in time, I think I Would want to annotate each tool listed on the Glitch Tools page. For now I only have the link pointing to that list.

Feel free to offer more suggestions!
